language: go
dist: trusty

go:
- 1.14

install:
  - go get github.com/stretchr/testify/assert

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script: make test

branches:
  only:
    - master

